name: Common Workflow

on:
  repository_dispatch:
    types: [run-common-workflow]

jobs:
  common-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Common Script
        run: ./path/to/common_script.sh
        env:
          COMMON_SECRET: ${{ secrets.COMMON_SECRET }}
